// Generated by CoffeeScript 1.8.0

/*
  Empty Disk Cache
    (C) あかつきみさき(みくちぃP)

  このスクリプトについて
    「ディスクキャッシュを空にする」コマンドを実行します.

  使用方法
    Startup,Shutdownフォルダーのどちらかに入れるか,スクリプトを実行から実行してください.

  動作環境
    Adobe After Effects CC以上

  バージョン情報
    2014/10/20 Ver 1.0.0 Release
 */

(function() {
  var EDCData, emptyDiskCache, runAEVersionCheck;

  EDCData = (function() {
    var canRunVersionC, canRunVersionNum, guid, scriptName, scriptURLName, scriptURLVersion, scriptVersionNumber;
    scriptName = "Empty Disk Cache";
    scriptURLName = "EmptyDiskCache";
    scriptVersionNumber = "1.0.0";
    scriptURLVersion = 100;
    canRunVersionNum = 12.0;
    canRunVersionC = "CC";
    guid = "{5A24F61A-8A16-41F7-A892-603D57CA59B7}";
    return {
      getScriptName: function() {
        return scriptName;
      },
      getScriptURLName: function() {
        return scriptURLName;
      },
      getScriptVersionNumber: function() {
        return scriptVersionNumber;
      },
      getScriptURLVersion: function() {
        return scriptURLVersion;
      },
      getCanRunVersionNum: function() {
        return canRunVersionNum;
      },
      getCanRunVersionC: function() {
        return canRunVersionC;
      },
      getGuid: function() {
        return guid;
      }
    };
  })();

  runAEVersionCheck = function(AEVersion) {
    if (parseFloat(app.version) < AEVersion.getCanRunVersionNum()) {
      alert("This script requires After Effects " + (AEVersion.getCanRunVersionC()) + " or greater.", EDCData.getScriptName());
      return false;
    } else {
      return true;
    }
  };

  emptyDiskCache = function() {
    var EMPTY_DISK_CACHE;
    EMPTY_DISK_CACHE = 10200;
    app.executeCommand(EMPTY_DISK_CACHE);
    return 0;
  };

  if ((typeof app !== "undefined" && app !== null ? app.project : void 0) == null) {
    return 0;
  }

  if (!runAEVersionCheck(EDCData)) {
    return 0;
  }

  emptyDiskCache();

  return 0;

}).call(this);
